# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abaf3a3e4c7fd9ddaa2f82ea7b67ea1ba3f48f535de4b4e230718116b7468183c698c3e8a1de38c1528484f99f7673e4688f820c86af84be2ba1a11218663a77

test:
  secret_key_base: 95f16d8e24016a9b1be7b594864214385ac7a612ee49d4a3004bc5cea89319925ea0ec69b3739b3ef00db107e2200e0e35cb311dc0d84b4cd8aeee37ed7ec3ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
